### ISSUE TITLE
Segmentation fault with "./qs 705074515857134286120871238142845541623" on WSL

### ISSUE THREAD

**Issue by maelhos** [michel-leonard/C-Quadratic-Sieve#1]
Hello, 
I am very gratefull for this project and would like to support it (threading/GPU would be nice)...
Everything seem to work fine most of the time but on Linux WSL at least... i get some segfaults every now an then :
`27. 705074515857134286120871238142845541623 = Segmentation fault`

The number 705074515857134286120871238142845541623 gives error for me, I tried with -O1... same
I'll dig in a bit more with a debugger...

**Comment by michel-leonard** [comment]
Hello, **thank you** for your interesting message.

You found an interesting issue because in the particular case you showed:

_the assertion "qs->iterative_list[3] is greater than qs->s.data[i].prime_index" did not hold._

To solve this issue, I proposed (iteration_part_2) to add an if statement which ensures the inequality. _The new if statement represent a low overhead for the factorizer, because its branching is highly predictable._

Best wishes.

**Comment by michel-leonard** [comment]
Hello, thank you for your interesting post, I think the optimization level isn't related to the issue.

You found an issue because in the particular case you showed :

the assertion "qs->iterative_list[3] is greater than qs->s.data[i].prime_index" did not hold.

An alternative solution would be to increase the value of qs->iterative_list[3] in qs_parametrize. But to solve this issue, I proposed to add an if statement which ensures the above inequality holds. The newly added if statement took place at the beginning of a small loop, it should generally print an imperceptible overhead to the iteration_part_2 function.

Hope you're ok, best wishes.

**Comment by michel-leonard** [comment]
Hello, **thank you** for your interesting post, I think the optimization level isn't related to the issue.

You found an issue because in the particular case you showed :

_the assertion "`qs->iterative_list[3]` is greater than `qs->s.data[i].prime_index`" did not hold._

An alternative solution would be to increase the value of `qs->iterative_list[3]` in _qs_parametrize_. But to solve this issue, I proposed to **add an if statement** which ensures the above inequality holds. _The newly added if statement took place at the beginning of a small loop, it should generally print an imperceptible overhead to the iteration_part_2 function_.

Hope you're ok, best wishes.

**Comment by maelhos** [comment]
thank you very much, it seem to fix it ... I want to work on QS for my TIPE (je suis en prepa) so i really enjoy your implementation of it...
